name: Attapon_Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest app.py > test_output.txt 2>&1
          if grep -q "FAILED" test_output.txt; then
            echo "Tests failed. Logging to error_log.txt."
            cp test_output.txt error_log.txt
            exit 1  # Markerar steget som fail
          else
            echo "Tests passed."

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_ATTAPON_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ATTAPON_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: docker build . -t attaponsayod/attapon:weather_app

      - name: Push Docker image
        run: docker push attaponsayod/attapon:weather_app
