name: Python OpenWeatherMap App CI/CD

# Triggar workflow när du pushar till main-branchen eller skapar en pull request t
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Definierar jobben som ska köras
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Steg 1: Checka ut koden från repositoryt
    - name: Check out code
      uses: actions/checkout@v2

    # Steg 2: Installera Python och beroenden
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Steg 3: Köra tester 
    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Steg 4: Hämta data från OpenWeatherMap API med din API-nyckel
    - name: Fetch Weather Data
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        python app.py
