name: Attapon_Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      log_errors: 
        description: "Generar error log om tests failar (True or False)"
        required: true
        default: "True" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: run_tests
        run: |
          python -m unittest app.py > test_output.txt 2>&1
          if grep -q "FAILED" test_output.txt; then
            echo "Tests failed."
            echo "test_result=failed" >> $GITHUB_ENV
          else
            echo "Tests passed."
            echo "test_result=passed" >> $GITHUB_ENV
          fi

      - name: Handle logs if tests fail and logging is enabled
        if: env.test_result == 'failed' && inputs.log_errors == 'True'
        run: |
          echo "Generating error log artifact..."
          cp test_output.txt error_log.txt

      - name: Upload error log artifact
        if: inputs.log_errors == 'True' && env.test_result == 'failed'
        uses: actions/upload-artifact@v3
        with:
          name: error_log
          path: error_log.txt

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_ATTAPON_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ATTAPON_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: docker build . -t attaponsayod/attapon:weather_app

      - name: Push Docker image
        run: docker push attaponsayod/attapon:weather_app
