name: Deploy Application

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Initial job
        run: echo "Starting deploy workflow."

  build:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t attaponsayod/attapon:latest .
      
      - name: Save Docker Image as TAR file
        run: |
          docker save attaponsayod/attapon:latest -o yourimage.tar

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./yourimage.tar

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ATTAPON_DOCKER_USERNAME }}
          password: ${{ secrets.ATTAPON_DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker push attaponsayod/attapon:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ATTAPON_AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        run: echo "Deploying to Azure..."
