name: attapon Test Application

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: 'Enable error logging for failed tests'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests
        continue-on-error: ${{ github.event.inputs.log_errors == true }}
      
      - name: Log Error if Tests Fail
        if: failure() && github.event.inputs.log_errors == 'true'
        run: echo "Error: Tests failed" > error_log.txt
