name: attapon_test_application

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: 'Enable error logging for failed tests'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and save output to log
      id: run_tests
      run: |
        python -m unittest discover -s tests | tee test_output.txt
      continue-on-error: true

    - name: Check for test failures and log if any
      if: failure() && inputs.log_errors == 'true'
      run: |
        echo "Tests failed. Saving log to logg.txt."
        cp test_output.txt logg.txt
      continue-on-error: true

    - name: Upload log file (optional for access in GitHub)
      if: failure() && inputs.log_errors == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: test-logs
        path: logg.txt
