name: Debug Secrets Access

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug Secrets Access
        run: |
          echo "DOCKER_ATTAPON_USERNAME=${{ secrets.DOCKER_ATTAPON_USERNAME }}"
          echo "DOCKER_ATTAPON_PASSWORD=${{ secrets.DOCKER_ATTAPON_PASSWORD }}"
