name: Gabriel Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t gabrielsayod/gabrielapp:latest .
          
      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ./gabrielapp_image.tar
