name: Pipeline 

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Initial job
        run: echo "Starting deploy workflow."

  build:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t gabrielheido/gabriel:latest .
      
      - name: Save Docker Image as TAR file
        run: |
          docker save gabrielheido/gabriel:latest -o yourimage.tar

      
      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
         name: docker-image
         path: ./yourimage.tar

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: ./

      - name: Load Docker Image from TAR file
        run: |
          docker load -i yourimage.tar

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_GABRIEL_USERNAME }}
          password: ${{ secrets.DOCKER_GABRIEL_PASSWORD }}
      - name: Log in to Docker Hub
        env:
         DOCKER_USER: ${{ secrets.DOCKER_GABRIEL_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_GABRIEL_PASSWORD }}
        run: |
         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: docker build . -t gabrielheido/gabriel:weather_app

      - name: Push Docker image
        run: docker push gabrielheido/gabriel:weather_app


      - name: Push Docker Image to DockerHub
        run: |
          docker push gabrielheido/gabriel:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
         if grep -q "FAILED" test_output.txt; then
            echo "Tests failed. Logging to error_log.txt."
            cp test_output.txt error_log.txt
            exit 1  # Markerar steget som fail
          else
            echo "Tests passed."
          fi
