name: Gabriel Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -R  # För att kontrollera att Dockerfile finns i rotkatalogen

      - name: Build Docker image
        run: docker build -t myapp .
