name: Pipeline

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Generera error log om tester misslyckas (True eller False)"
        required: true
        default: "True"

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Initial job
        run: echo "Starting deploy workflow."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest app.py > test_output.txt 2>&1
          if grep -q "FAILED" test_output.txt; then
            echo "Tests failed."
            echo "test_result=failed" >> $GITHUB_ENV
            exit 1
          else
            echo "Tests passed."
            echo "test_result=passed" >> $GITHUB_ENV
          fi

      - name: Handle logs if tests fail and logging is enabled
        if: failure() && inputs.log_errors == 'True'
        run: |
          echo "Generating error log artifact..."
          cp test_output.txt error_log.txt

      - name: Upload error log artifact
        if: inputs.log_errors == 'True' && failure()
        uses: actions/upload-artifact@v3
        with:
          name: error_log
          path: error_log.txt

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_GABRIEL_USERNAME }}
          password: ${{ secrets.DOCKER_GABRIEL_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t gabrielheido/gabriel:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push gabrielheido/gabriel:latest

      - name: Publish Docker Image to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gabbes app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "gabrielheido/gabriel:latest"
