name: CI/CD Pipeline

on:
  workflow_dispatch:  # Detta gör att pipelinen kan triggas manuellt
    inputs:
      log_errors:
        description: 'Skapa loggar om tester misslyckas'
        required: true
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python (eller annat språk)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # eller motsvarande för ditt språk

      - name: Run tests
        run: |
          pytest tests/  # eller motsvarande för ditt testsystem
        continue-on-error: true  # För att kunna kontrollera resultatet av testerna

  build:
    needs: test  # Detta jobb körs först efter att testjobbet är klart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker image to DockerHub
        if: success()  # Om testerna lyckades
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_GABRIEL_USERNAME }}
          password: ${{ secrets.DOCKER_GABRIEL_PASSWORD }}
          repository: gabrielheido/gabriel
          tags: latest

  deploy:
    needs: build  # Detta jobb körs efter att build-jobbet är klart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: myazureapp
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./
