name: Pipeline 

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Initial job
        run: echo "Starting deploy workflow."

  build:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t gabrielsayod/gabriel:latest .
      
      - name: Save Docker Image as TAR file
        run: |
          docker save gabrielsayod/gabriel:latest -o yourimage.tar
          
      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./yourimage.tar

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: ./

      - name: Load Docker Image from TAR file
        run: |
          docker load -i yourimage.tar

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_GABRIEL_USERNAME }}
          password: ${{ secrets.DOCKER_GABRIEL_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker push gabrielheido/gabriel:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GABRIEL_AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp create --name gabriel_app --resource-group project --plan Grupp_projekt --deployment-container-image-name gabrielsayod/gabriel:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Fetch Weather Data
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          python app.py
          
