name: DevOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      log_errors:
        description: 'Should error logs be generated?'
        required: true
        default: 'false'

jobs:
  # Byggjobb
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (eller annan teknikstack du använder)
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true  # Det gör så att pipelinen fortsätter även om testerna misslyckas, kan justeras senare baserat på inputs

  # Docker image jobb
  docker:
    needs: build  # Det här jobbet körs efter att build-jobbet är klart
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          docker build -t myapp .
      
      - name: Publish Docker image to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push myapp
